on:
  # The issues event below is only needed for the default (auto) mode,
  # you can remove it otherwise
  issues:
    types: [assigned]
  # The issue_comment event below is only needed for the ChatOps mode,
  # you can remove it otherwise
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setting up environment variables
        run: |
          BRANCH_PREFIX=PLAY
          ISSUE_NUMBER=${{ github.event.issue.number }}
          echo "BRANCH_NAME=$BRANCH_PREFIX-`printf '%03d\n' $ISSUE_NUMBER`" >> $GITHUB_ENV

      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
